#!/usr/bin/env python2
# coding = utf8

import sys
import re
import os
import markdown
import codecs

TAG_FOR_WRAP = '{{{slides}}}'
WRAP_FILE = './resources/wrap.html'
SECTION_WRAPER_FILE = './resources/section.html'
SECTION_SPLIT_PATTERN = re.compile(r'\.{3,}')
HTML_TAG_PATTERN = re.compile('<.*?>')
TITLE_PATTERN = re.compile('<h1>(.*?)</h1>')
SUBSLIDE_PATTERN = re.compile(r'<(?P<tag>.*?)>;')


def usage():
    print '''Usage:
        markdeck file1 [file2 [file3]...]'''


def write_to_file(filename, strings):
    fobj = None
    try:
        fobj = codecs.open(filename, 'w', encoding="utf-8")
        fobj.write(strings)
    except IOError:
        print 'write to file `%s` error' % filename
    finally:
        if fobj is not None:
            fobj.close()


def get_file_content_safely(filename):
    '''get_file_content_safely: open file and read all file content'''
    fobj = None
    try:
        fobj = codecs.open(filename, 'r', encoding='utf-8')
        content = fobj.read().strip()
    except IOError:
        print 'read file `%s` error' % filename
        content = '<h1>Read File Error</h1>'
    finally:
        if fobj is not None:
            fobj.close()
    return content


def render_section(section):
    '''render_section: render a section'''
    md = markdown.Markdown(extensions=['tables', 'nl2br'])
    html = md.convert(section)
    _wrapper = get_file_content_safely(SECTION_WRAPER_FILE)
    try:
        result = _wrapper % html
    except TypeError:
        result = _wrapper
        print 'missing `%%s` in `%s`' % WRAP_FILE


    # re tag codes
    result = result.replace('<p><code>', '<pre><code>')\
        .replace('</code></p>', '</code></pre>')


    # render subslide
    result = SUBSLIDE_PATTERN.sub(r'<\g<tag> class="slide">', result)
    # print result
    return result


def render_file(filename):
    '''render_file: render the mardown'''
    content = get_file_content_safely(filename)
    sections = SECTION_SPLIT_PATTERN.split(content)

    # render each section
    rendered_list = []
    for section in sections:
        rendered_list.append(render_section(section))

    # get title for html
    try:
        title = TITLE_PATTERN.search(rendered_list[0]).groups()[0]
        title = HTML_TAG_PATTERN.sub('', title)
    except (IndexError,AttributeError):
        title = 'MarkDeck'
        print 'need a h1 in first section for html title'
    return title, ''.join(rendered_list)


def wrap(title, html):
    '''wrap: wrap slides with the htmls'''
    _wrapper = get_file_content_safely(WRAP_FILE)
    # print _wrapper
    try:
        result = _wrapper % TAG_FOR_WRAP
    except TypeError:
        result = _wrapper
        print 'missing `%%s` in `%s`' % WRAP_FILE

    # add title
    result = result.replace('<title></title>', '<title>%s</title>' % title)
    return result.replace(TAG_FOR_WRAP, html)


def main(argv):
    for filename in argv:
        name, extension = os.path.splitext(filename)
        if extension in {".md", ".markdown"}:
            print 'rendering', filename
            write_to_file('%s.html' % name, wrap(*render_file(filename)))


if __name__ == '__main__':
    if len(sys.argv) < 2:
        usage()
    else:
        main(sys.argv[1:])
